### ISSUE TITLE
Cut text reappears when leaving the field

### ISSUE THREAD

**Issue by matssigge** [autoNumeric/autoNumeric#527]
### Expected behavior
When I select all or part of the contents of an autoNumeric input field, cut the text out to the clipboard, 
and then leave the field, the contents of the field are left as they are.

### Actual behavior
When leaving the field after cutting out some text, the previous contents of the field are restored. This happens both if I select all the text or part of it.

### Steps to reproduce the problem
1. Using autoNumeric `v4.0.1` and the browser `Chrome` version `61` on `MacOS Sierra 10.12.6`,
2. I used no options
3. Initialized my AutoNumeric object with the call `new AutoNumeric(domElement)`,
4. I placed the cursor in the input field and typed 12345. The contents of the field was at this point `12,345.00`.
5. I pressed Cmd+A (i.e. select all), Cmd+X (Cut). At this point the field was empty.
5. I pressed the tab key, and the text `12,345.00` reappears in the field.

I've tried using Safari 11 and Firefox 54, both on MacOS 10.12.6, and also IE11 on Windows 7 (I happened to have a VM running) and get the same result. 

### Complete example
There is a codepen at https://codepen.io/matssigge/pen/rYavLG, but the code below is all that is needed to reproduce the problem.

```
<!DOCTYPE html>
<html>
<head>
    <script src="https://unpkg.com/autonumeric@4.0.1/dist/autoNumeric.min.js"></script>
</head>
<body>
<input id="foobar" type="text" name="foobar">
<script>
    new AutoNumeric(document.getElementById("foobar"));
</script>
</body>
</html>
```

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this @matssigge.

However I cannot reproduce the bug you are describing.
I tried [more use cases](https://codepen.io/AnotherLinuxUser/pen/BmyGBV) with/without a predefined value, by selecting only a part of the number or the whole input content, and whenever I `blur` the input either by mouse clicking elsewhere or using the `Tab` key, the value does not reappear.

I did those tests using Firefox 56 and Chrome 61 under Linux, and also tried with IE11 under Windows 7 (in a vm) and everything was working ok.

Perhaps you have custom extension messing with AutoNumeric, but that sounds unlikely?

Could you try my codepen? I'm using the lastest AutoNumeric version `4.1.0-beta.16` and perhaps the bug (I was not aware of) got fixed along the way!

**Comment by matssigge** [comment]
I agree that this seems like a strange bug - it feels like such an obvious thing that it would have been caught by someone before. That's also why I tested several different browsers. Unfortunately, I still have the same behavior in your codepen. I also tried that same codepen with my iPhone and iPad, and on my wife's Android phone, and it's the same thing everywhere. I'm still second-guessing myself, trying to think what I might be doing to bring this on myself, but I can't think of anything that goes across platforms and devices, especially the windows VM and my wife's phone.

I can't think of anything more to try right now. I'll try to find the time to dig further tomorrow, and maybe set some breakpoints and/or add some logging.

**Comment by AlexandreBonneau** [comment]
Ok my bad, it turns out I was not using `Ctrl+x` to cut the whole input content, but the Fn+cut shortcut found on my Dvorak Typematrix keyboard.

I guess I just found out after those many years this shortcut does not only mimic `Ctrl+x` but does *something more*!

I could reproduce the bug using the `Ctrl` + `x` keys.
It's weird that such a bug could live in the codebase for that long.
Perhaps everybody using the code is a Dvorak user too? 😎

**Comment by matssigge** [comment]
That is very interesting. I'm just glad I'm not imagining things. 😊

**Comment by TomSaporito** [comment]
The issue is you need to use .set method on change.  That will set the input value in memory and ensure it's correct.

**Comment by AlexandreBonneau** [comment]
This is fixed in `4.1.0-beta.24`

**Comment by matssigge** [comment]
Commenting here as well as in #576. I'm still seeing the same issue with 4.2.12. I've updated the codepen (https://codepen.io/matssigge/pen/rYavLG/) to use 4.2.12, so it's easily reproducible.
