### ISSUE TITLE
Missing support for very small or very big numbers displayed by Javascript as scientific numbers

### ISSUE THREAD

**Issue by alexturpin** [autoNumeric/autoNumeric#553]
### Current behavior
AutoNumeric does not round properly for numbers that are so small that JavaScript displays them as scientific / exponential notation when converted to string.

### Expected behavior
AutoNumeric should properly round those numbers.

### Steps to reproduce the problem
1. Use autoNumeric version `4.1.0`
2. In the browser `Chrome` version `63`
3. On the `Windows 10` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
var an = new AutoNumeric('#test', { decimalPlaces: 2 });
```
5. Use `.set` to set the AutoNumeric instance to a reall small value such as `123/10000000000000` (`1.23e-13`).
6. Field shows up as `1.23` instead of `0.00`.

### Link to live example
https://codepen.io/anon/pen/RQyBMZ

I'm pretty sure this stems from `_roundValue` parsing the numbers as strings and just not taking exponential notation into account. For now I might patch my local version [with something like this](https://gist.github.com/jiggzson/b5f489af9ad931e3d186) but I'm sure there's a cleaner way to do it for the codebase.

**Comment by alexturpin** [comment]
To anyone also experiencing this issue, this is the patch I did for now:

```
diff --git a/src/AutoNumeric.js b/src/AutoNumeric.js
index ca4e5af..8e6709a 100644
--- a/src/AutoNumeric.js
+++ b/src/AutoNumeric.js
@@ -5404,6 +5404,31 @@ To solve that, you'd need to either set \`decimalPlacesRawValue\` to \`null\`, o
         return this._roundValue(value, settings, Number(settings.decimalPlacesShownOnBlur));
     }

+    static _scientificToDecimal(num) {
+        //if the number is in scientific notation remove it
+        if (/\d+\.?\d*e[\+\-]*\d+/i.test(num)) {
+            var zero = '0',
+                parts = String(num).toLowerCase().split('e'), //split into coeff and exponent
+                e = parts.pop(),//store the exponential part
+                l = Math.abs(e), //get the number of zeros
+                sign = e/l,
+                coeff_array = parts[0].split('.');
+
+            if (sign === -1) {
+                num = zero + '.' + new Array(l).join(zero) + coeff_array.join('');
+            }
+            else {
+                var dec = coeff_array[1];
+                if (dec) {
+                    l = l - dec.length;
+                }
+                num = coeff_array.join('') + new Array(l+1).join(zero);
+            }
+        }
+
+        return num;
+    };
+
     /**
      * Round the input value using the rounding method defined in the settings.
      * This function accepts multiple rounding methods. See the documentation for more details about those.
@@ -5424,6 +5449,7 @@ To solve that, you'd need to either set \`decimalPlacesRawValue\` to \`null\`, o

         //TODO Divide this function to make it easier to understand
         inputValue = (inputValue === '') ? '0' : inputValue.toString();
+        inputValue = this._scientificToDecimal(inputValue);
         if (settings.roundingMethod === AutoNumeric.options.roundingMethod.toNearest05 ||
             settings.roundingMethod === AutoNumeric.options.roundingMethod.toNearest05Alt ||
             settings.roundingMethod === AutoNumeric.options.roundingMethod.upToNext05 ||

```

**Comment by AlexandreBonneau** [comment]
This is fixed in `v4.2.1`.

@alexturpin Thanks for pointing out the cause of that bug, that helped immensely!

I'd recommend updating your AutoNumeric version to `4.2.1` now, since the `_scientificToDecimal()` function you pasted above fails for some valid scientific notations (`'1.23456789e4'` for instance) :open_mouth:

**Comment by alexturpin** [comment]
@AlexandreBonneau thanks for the quick fix and release and the great work as always! Absolutely will do.

**Comment by adrianmroz** [comment]
Hi, I believe bug is still present in 4.6.0. Reproduction sandbox: https://codesandbox.io/s/adoring-clarke-y7xbp?file=/src/index.js
