### ISSUE TITLE
On rapid event wheel emissions, deltaY of value 0 can be emitted and makes AutoNumeric throw an error

### ISSUE THREAD

**Issue by DaveK-Rocketmakers** [autoNumeric/autoNumeric#776]
### Current behavior

Currently having the following exception raised by the component when scrolling fast (easily done on sensitive touchpads)

```
The event passed as a parameter is not a valid wheel event, 'wheel' given.
```

### Expected behavior
For this error not to be thrown

### Steps to reproduce the problem
1. Go to https://autonumeric.org/ and focus on the currency input available in Chrome or Firefox on an Apple Macbook M1 2021
2. Scroll up and down on the touchpad

### Link to live example
https://autonumeric.org/

**Comment by DaveK-Rocketmakers** [comment]
It looks like this is caused because `deltaY` is zero. Below is the contents of the raised event

```
Object { e: wheel }
{
    e: wheel { target: input#quux.pureJsManagedInput, buttons: 0, clientX: 988, … }
    {
        altKey: false
        bubbles: true
        button: 0
        buttons: 0
        cancelBubble: false
        cancelable: true
        clientX: 988
        clientY: 146
        composed: true
        ctrlKey: false
        currentTarget: null
        defaultPrevented: false
        deltaMode: 0
        deltaX: -1
        deltaY: 0
        deltaZ: 0
        detail: 0
        eventPhase: 0
        explicitOriginalTarget: <input id="quux" class="pureJsManagedInput" type="text" placeholder="via Pure JS" name="quu" value="">
        isTrusted: true
        layerX: 146
        layerY: 22
        metaKey: false
        movementX: 0
        movementY: 0
        offsetX: 0
        offsetY: 0
        originalTarget: Restricted {  }
        pageX: 988
        pageY: 159
        rangeOffset: 0
        rangeParent: null
        relatedTarget: null
        returnValue: true
        screenX: 988
        screenY: 296
        shiftKey: false
        srcElement: <input id="quux" class="pureJsManagedInput" type="text" placeholder="via Pure JS" name="quu" value="">
        target: <input id="quux" class="pureJsManagedInput" type="text" placeholder="via Pure JS" name="quu" value="">
        timeStamp: 3996
        type: "wheel"
        view: Window file:///Users/dave/repos/rocketmakers/autoNumeric/test/e2e/index.html
        wheelDelta: 3
        wheelDeltaX: 3
        wheelDeltaY: 0
        which: 1
        x: 988
        y: 146
    }
}
```

**Comment by AlexandreBonneau** [comment]
This cannot be caused because `deltaY`  is equal to `0`.
This error message is only thrown when the event element passed is not an instance of `WheelEvent`, or if the deltaY value is undefined, null or equal to '', not when deltaY is equal to 0.

However, based on the event info you pasted above, I fail to see why this is thrown. Perhaps this display of data converts null values to '0'?
Could you please check the real value and type of deltaY?

Since I do not have a M1, it'll be a bit difficult to find the cause of this bug, unfortunately.

**Comment by DaveK-Rocketmakers** [comment]
Apologies, I am getting a mixture of errors around this same behaviour - a mostly sideways swipe on the mac trackpad.

> The event passed as a parameter is not a valid wheel event, 'wheel' given.

The above event I'm getting on the main website. When I attach the following code

> document.getElementById("test").addEventListener('wheel', e => console.log({ isUndefinedOrNullOrEmpty: e.deltaY == null || e.deltaY === void(0) || '' === e.deltaY, isType: e instanceof WheelEvent }))

I get the following result before the error is thrown

> { isUndefinedOrNullOrEmpty: false, isType: true }

Which implies it shouldn't be hitting the error defined in the codebase. I'm not sure if the website is using the latest version of the component.

> The event is not a 'wheel' event

The above error is recreated on the e2e test components by doing the same action, which is called as part of line 7616 which would be caused by deltaY being 0 (as per the posted object)

**Comment by AlexandreBonneau** [comment]
Indeed, `the event is not a 'wheel' event` is returned when AutoNumeric cannot reliably find if the given wheel event has a positive or negative deltaY.
Which means that if deltaY is equal to 0, then 
```js
AutoNumericHelper.throwError(`The event is not a 'wheel' event.`);
```
is called.

I've pushed `v4.10.1` that should fix the issue you are encountering; please test if that really fixed it :)

**Comment by DaveK-Rocketmakers** [comment]
Thank you for the quick update. I'll test it out when I'm next on the project, which should be by the new year.

**Comment by DaveK-Rocketmakers** [comment]
Hello. I've had a chance to have a look, and it's unfortunately still failing. I think it's due to this [new method](https://github.com/autoNumeric/autoNumeric/blob/next/src/AutoNumericHelper.js#L819), where it should be 

> return this.isWheelEvent(wheelEvent) && !this.isUndefinedOrNullOrEmpty(wheelEvent.deltaY) && wheelEvent.deltaY === 0;

where we don't want deltaY to be undefined or null or empty? Or ignore that bit of the check altogether as we're checking if it equals zero.

**Comment by AlexandreBonneau** [comment]
Ah yes of course, we do not want `deltaY` to be undefined or null or empty :)
But we still need to check if it's not 'undefined' before trying to access the property.

Could you please test the latest commit?

**Comment by DaveK-Rocketmakers** [comment]
Yeah that seems to have fixed the issue. Thank you :)

**Comment by HenryZhang-ZHY** [comment]
@AlexandreBonneau I noticed that the latest fix hasn't been published to NPM yet. I really appreciate your work and would love to have this fix included in my project as soon as possible.

Could you please consider publishing the latest fix to NPM? It would be incredibly helpful for me.

**Comment by AlexandreBonneau** [comment]
Sure, you'll find the fix in `4.10.3` !

**Comment by bsw-wtg** [comment]
There seems to be a problem with the 4.10.3 npm package:
https://registry.npmjs.org/autonumeric/-/autonumeric-4.10.3.tgz
The `src/` files are the latest version 4.10.3, but the `dist/` files still have version 4.10.2 and don't include the fix. 
Has something gone wrong with the deploy?

**Comment by AlexandreBonneau** [comment]
Yes, something did go wrong with the `build` step not correctly executing!
This is fixed in `4.10.4`, normally :)
